Feature/wp30 28 usuario visualiza detalhes de uma tarefa
tribos-dev/produdoro-t2022-01-s03 pull request #3
Opened 2022-10-06 00:00 UTC by Leonardo2299

2022-10-07 11:32 UTC, vinireis requested changes

2022-10-07 11:32 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/pomodoro/application/service/PomodoroApplicationService.java
> +
Por que adicionou depedências que não foram utilizadas e linhas em branco também?

2022-10-07 11:32 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/application/api/TarefaAPI.java
> +    @GetMapping("/detalha/{idTarefa}")
nessa URI não deve existir o termo "detalha". "/{idTarefa}" já o suficiente! É uma boa prática nunca utilizar verbos em urls!

2022-10-07 11:32 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/application/api/TarefaRequest.java
>  public class TarefaRequest {
Mais uma vez imports não utilizados!

2022-10-07 11:32 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/usuario/application/api/UsuarioController.java
> +	//}
Não entendi isso aqui!

2022-10-07 21:20 UTC, Leonardo2299 commented on src/main/java/dev/wakandaacademy/produdoro/pomodoro/application/service/PomodoroApplicationService.java
> +
Corrigido. Dependências e linhas em branco foram removidas.

2022-10-07 21:22 UTC, Leonardo2299 commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/application/api/TarefaAPI.java
> +    @GetMapping("/detalha/{idTarefa}")
Corrigido. Anotado para aprendizado.

2022-10-07 21:29 UTC, Leonardo2299 commented on src/main/java/dev/wakandaacademy/produdoro/usuario/application/api/UsuarioController.java
> +	//}
Corrigido. Isso foi "lixo" que tinha ficado no código, removido já.

2022-10-12 00:04 UTC, Maabia approved these changes

2022-10-12 00:43 UTC, Maabia approved these changes

2022-10-12 00:44 UTC, Maabia approved these changes

2022-10-12 00:45 UTC, Maabia approved these changes

2022-10-12 00:45 UTC, Maabia approved these changes

2022-10-12 00:47 UTC, merged